### ISSUE TITLE
Add more ways to end the simulation

### ISSUE THREAD

**Issue by PatatasDelPapa** [elshize/simrs#23]
I'm doing some basic benchmarks comparing this library to mine (this one is faster btw) and while doing the models I notice that I didn't find a way to make the simulation run a maximum of 1000 seconds. I had to use
 ```rust
 while simulation.step() && clock.time() < limit {}
```
The final time ended up being 1002 seconds. 

One solution it comes to mind is using an Enum like `desim`. 
```rust
pub enum EndCondition {
    Time(Duration), // desim uses f64 here
    NoEvents,
    NSteps(usize),
}
// In Simulation implementation block
pub fn run(&mut self, until: EndCondition) { ... }
```

**Comment by PatatasDelPapa** [comment]
I did the same model with desim, and while not exactly the same (because of design problems I couldn't emulate some thing) I used `EndCondition::Time(1000.0)` and the end result was `1008.0` so it also doesn't work, I solved this on my library by inserting an event at limit, in this case 1000 seconds, so when that event is pulled it ends the simulation. It feels hacky because it's a special event with an special if clause to search for it to end the simulation.

**Comment by elshize** [comment]
Hi @PatatasDelPapa I think the problem with stopping at exactly time `T` is simply because you'd need an actual event at that time. More likely, you'll have an event starting at `T - epsilon` and ending at `T + epsilon`, and you won't get a chance to end the event while processing it (without significant changes to event handling).

So the fundamental problem is not the implementation per se, it's that this is discrete simulation, and there's no half-steps, and thus you can't force it to last exactly `T` in a sense that the last tick was at `T`.

You can force the simulation to exclude any events that end after `T`, and thus arrive at the facto state of the simulation at `T`, ignoring any ongoing stuff. But note that the end of the last event will still be likely less than `T`. I think this is perhaps the correct behavior when setting the simulation duration.

I wouldn't like to actually include the end condition event in the sim results, but it is in fact a nice way of internally implementing it. The simulation will then end with the timer at `T` but the last event finished at `T - epsilon`, where epsilon could be 0 or more.

Let me have a look at the code soon, I think this should be fairly straight forward to implement.

**Comment by PatatasDelPapa** [comment]
Yeah stopping exactly at `T` maybe isn't necessary but adding more ways to stop the simulation does sounds good enough.

**Comment by elshize** [comment]
@PatatasDelPapa FYI, I pushed some updates here: https://github.com/elshize/simrs/pull/24 Haven't written the tests yet; if you have any comments/questions in the meantime, feel free to drop them either here or under the PR.
